#! /bin/sh

bspc config border_width        4
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true
bspc config top_padding         20
#bspc config right_padding 	16
#bspc config left_padding	16
#bspc config bottom_padding	16
bspc monitor -d I II III IV V
bspc config focus_follows_pointer true

# colours
bspc config focused_border_color "#7691b8"
bspc config normal_border_color "#7691b8"
bspc config presel_border_color "#7691b8"


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#panel &
